syntax on

"Vundle Start
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-syntastic/syntastic'
Plugin 'embear/vim-uncrustify'
Plugin 'fatih/vim-go'
Plugin 'cespare/vim-toml'
Plugin 'prettier/vim-prettier'
Plugin 'leafgarland/typescript-vim'
Plugin 'junegunn/fzf'
Plugin 'vim-scripts/DrawIt'
call vundle#end()
filetype plugin indent on
"Vundle End

"Basic Vim Config
set tabstop=2
set noexpandtab
set shiftwidth=2
set backspace=indent,eol,start
set background=light
set noswapfile
set backup
set backupdir=~/.backups//
set t_Co=256
set background=dark

"Variables
let g:uncrustify_config_file = '~/.uncrustify.cfg'
let g:go_fmt_command = 'goimports'
let g:prettier#autoformat = 1
let g:prettier#autoformat_require_pragma = 0

"c 
autocmd FileType c setlocal noexpandtab tabstop=8 softtabstop=8 shiftwidth=8
autocmd FileType cpp setlocal noexpandtab tabstop=8 softtabstop=8 shiftwidth=8
autocmd Filetype c autocmd BufWritePre <buffer> call Uncrustify()
autocmd Filetype cpp autocmd BufWritePre <buffer> call Uncrustify()
