#
# ~/.zrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
[[ $TERM == st-256color ]] && exec tmux attach

autoload -Uz compinit
compinit

PROMPT='%F{yellow}[%n%f@%F{green}%B%m%b%f %F{yellow}%~]%f%F{cyan}$%f '

export LANG='en_US.UTF-8'

export GOPATH=$HOME/.go

export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.local/sbin
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/docs/scripts

alias ls='ls -lh'
alias gitlog='git log --oneline --decorate --all --graph'
alias prettyjson='python3 -m json.tool'
alias rg='rg --color ansi'
alias less='less -R'

# Server Alias
alias msync='rsync -av adam@vega2:/ext2/music/ /home/adam/media/music/flacs'
alias wmpull='rsync -av adam@vega2:/ext2/web_music/new/ /home/adam/media/music/webrips'
alias wmpush='rsync -av /home/adam/media/music/webrips/ adam@vega2:/ext2/web_music/new '

# Games
alias doom='crispy-doom -iwad doom.wad -merge sigil.wad'
alias wolf='wolf3d --windowed-mouse'
alias quake='quakespasm -basedir /usr/local/share/games/quake'
alias quake3='cd /home/adam/src/ioquake3/build/release-linux-x86_64 && ./ioquake3'
alias mvc2='redream ~/games/roms/dreamcast/Marvel\ vs.\ Capcom\ 2\ \(USA\)/Marvel\ vs.\ Capcom\ 2\ \(USA\).cue'
