syntax on

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
"My Plugins Start
Plugin 'leafgarland/typescript-vim'
"My Plugins End

call vundle#end()
filetype plugin indent on
