syntax on

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
"My Plugins Start
Plugin 'leafgarland/typescript-vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'fatih/vim-go'
Plugin 'scrooloose/nerdtree'
"Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'vim-syntastic/syntastic'
Plugin 'rust-lang/rust.vim'
"My Plugins End

call vundle#end()
filetype plugin indent on

set expandtab
set tabstop=2
set shiftwidth=2

"autocmd vimenter * NERDTree
set noswapfile

set guioptions-=T
set guifont=Consolas:h11:cANSI

let g:rustfmt_autosave = 1

set backspace=indent,eol,start
