syntax on

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
"My Plugins Start
Plugin 'leafgarland/typescript-vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'fatih/vim-go'
"Plugin 'scrooloose/nerdtree'
"Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'vim-syntastic/syntastic'
Plugin 'rust-lang/rust.vim'
Plugin 'embear/vim-uncrustify'
Plugin 'jparise/vim-graphql'
Plugin 'python/black'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'prettier/vim-prettier'
"My Plugins End

call vundle#end()
filetype plugin indent on

"Tabs
set tabstop=2
set noexpandtab
set shiftwidth=2

"autocmd vimenter * NERDTree
set noswapfile
set backup
set backupdir=~/.backups//

set guioptions-=T
set guifont=Hack\ 14

let g:rustfmt_autosave = 1
let g:vim_markdown_folding_disabled = 1


let g:go_fmt_command = "goimports"
"let g:go_auto_type_info = 1
"set updatetime=100

set backspace=indent,eol,start

autocmd Filetype c setlocal noexpandtab tabstop=8 softtabstop=8 shiftwidth=8
autocmd Filetype cpp setlocal noexpandtab tabstop=8 softtabstop=8 shiftwidth=8
"let g:syntastic_c_include_dirs = ['/usr/include']
let g:uncrustify_config_file = '~/.uncrustify.cfg'

autocmd Filetype c autocmd BufWritePre <buffer> call Uncrustify()
autocmd Filetype cpp autocmd BufWritePre <buffer> call Uncrustify()

"map <silent> <C-n> :NERDTreeToggle<CR>
map <silent> <C-x> :vert term<CR>

"let NERDTreeShowHidden=1

let g:syntastic_python_python_exec = '/usr/local/bin/python3'
let g:syntastic_python_checkers=['python3']

autocmd BufWritePre *.py execute ':Black'

let g:syntastic_javascript_checkers = ['eslint']

command JSONPretty :%!python -m json.tool

set laststatus=2
set statusline=%F

autocmd BufWritePre *.js execute ':Prettier'


" PICO-8
autocmd BufNewFile,BufRead *.p8 set syntax=lua filetype=lua
autocmd FileType lua noremap <buffer> <F8> :exec '!/Applications/pico-8/PICO-8.app/Contents/MacOS/pico8 -run' shellescape(@%,1)<cr>
let g:syntastic_ignore_files = ['*.p8']
