export ENV=$HOME/.zshrc
xsetroot -solid black &
while xsetroot -name "`date`"
do
	sleep 1
done &

if [ -x /usr/local/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
	eval `dbus-launch --sh-syntax --exit-with-x11`
fi

dwm
#startxfce4
#gnome-session
