#
# ~/.zrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

autoload -Uz compinit
compinit

PROMPT='%F{cyan}[%n%f@%F{magenta}%B%m%b%f %F{cyan}%~]%f%F{green}$%f '

export LANG='en_US.UTF-8'

export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/code/scripts

alias ls='ls -lh'
alias gitlog='git log --oneline --decorate --all --graph'
alias mame='cd ~/docs/games/mame && mame'
alias prettyjson='python3 -m json.tool'
